### ISSUE TITLE
CSV output is mangled 

### ISSUE THREAD

**Issue by scr512** [shirosaidev/diskover-web#9]
Version: 1.5.0-rc16
Docker Container: https://github.com/scr512/docker-diskover-web/blob/master/Dockerfile
When exporting a query to CSV, delimiting breaks... both in Windows land with Excel and with Linux tools (cut)

Example:
```
$ head -15 diskover_export_file\ \(1\).csv | cut -d, -f 14
filesize
1855808923
1872143765
1619683671
1864039435
1857076267
1850683799
1857484136
8056344320
2018-09-15T09:30:40.856155
2018-09-15T09:30:40.865604
2018-09-15T09:30:40.878265
2018-09-15T09:30:40.893790
2018-09-15T09:30:40.097447
2018-09-15T09:30:40.107179
```
I clearly expect to see filesize, not a timedate stamp

Here is the first 15 lines without parsing:
```
dupe_md5,extension,owner,tag,last_change,indexing_date,group,inode,last_modified,last_access,hardlinks,filename,worker_name,filesize,filehash,path_parent,tag_custom
,fsdb,user02,,2018-02-21T14:13:34,2018-09-16T19:07:42.457574,partner,3261587137,2018-02-21T14:13:34,2018-02-21T14:13:34,1,transient0.tran.fsdb,hpc-admin0.11061,1855808923,2d1e78abdd97f1ba0c7423b26f9ddcf7,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/sim/sim.raw,
,fsdb,user02,,2018-02-22T10:38:00,2018-09-16T19:07:42.316971,partner,3300252844,2018-02-22T10:38:00,2018-02-22T10:38:00,1,transient0.tran.fsdb,hpc-admin0.11061,1872143765,29e2a870aced3e73e42dab29d866e2d8,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/wl_header_update/VDDPE_OPTIMIZATION/sim/sim.raw,
,fsdb,user02,,2018-02-22T18:07:08,2018-09-16T19:07:42.343690,partner,3317985758,2018-02-22T18:07:07,2018-02-22T18:07:07,1,transient0.tran.fsdb,hpc-admin0.11061,1619683671,280b295ec628826abc241554b2e1fdba,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/wl_header_update/WDX4I_AST/CONLY/sim/sim.raw,
,fsdb,user02,,2018-02-22T18:41:35,2018-09-16T19:07:42.379715,partner,3322573322,2018-02-22T18:41:35,2018-02-22T18:41:35,1,transient0.tran.fsdb,hpc-admin0.11061,1864039435,5de9ed413df86ae1dc8e5f106c7aa81d,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/wl_header_update/WDX4I_AST/Header_wd/sim/sim.raw,
,fsdb,user02,,2018-02-22T14:50:33,2018-09-16T19:07:42.420287,partner,3312210146,2018-02-22T14:50:33,2018-02-22T14:50:33,1,transient0.tran.fsdb,hpc-admin0.11061,1857076267,3cb2c2cc2298d491d05ce96c7959ffe5,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/wl_header_update/WDX4I_AST/Reduce_footer/sim/sim.raw,
,fsdb,user02,,2018-02-22T14:41:14,2018-09-16T19:07:42.397875,partner,3297754556,2018-02-22T14:41:14,2018-02-22T14:41:14,1,transient0.tran.fsdb,hpc-admin0.11061,1850683799,4009b6cac7896686744a039c72cf432a,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/wl_header_update/WDX4I_AST/sim/sim.raw,
,fsdb,user02,,2018-02-22T07:39:42,2018-09-16T19:07:42.438273,partner,3292589808,2018-02-22T07:39:42,2018-02-22T07:39:42,1,transient0.tran.fsdb,hpc-admin0.11061,1857484136,47839a89213ccdbb601e24e38e6b5505,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user02/wl_header_update/sim/sim.raw,
,fsdb,user01,,2018-03-06T21:04:22,2018-09-15T09:35:22.213673,partner,3623915697,2018-02-28T23:15:28,2018-02-28T23:15:28,1,c0.fsdb,hpc-admin0.11061,8056344320,d0707d6d0fc8c281c07f78fe653952b9,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/r7/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X84m2fb1fs2w/full/setup_CLK_r_EMA_r/control,
hpc-admin0.11051,fsdb,2269263876,partner,5508efa3bc5e8e57c44db141cb3f3293,,2018-02-14T05:23:14,2018-02-15T21:28:00,user01,,,1,c0.fsdb,2018-09-15T09:30:40.856155,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/partner_partner_technologymy_company_sw_tool/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X16m2fb1fs2w/full/delay_CLK_r_Q_r/control,2805513528,2018-02-14T05:23:14
hpc-admin0.11051,fsdb,2972766162,partner,e8216289179972638df34f3c7e72fbc5,,2018-02-16T06:49:14,2018-02-16T06:49:14,user01,,,1,c0_new4.fsdb,2018-09-15T09:30:40.865604,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/partner_partner_technologymy_company_sw_tool/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X16m2fb1fs2w/full/delay_CLK_r_Q_r/control/ema,2947038418,2018-02-16T06:49:14
hpc-admin0.11051,fsdb,3162196612,partner,769c05ab6c33f016d5275f13dd063783,,2018-02-16T06:51:37,2018-02-16T06:51:37,user01,,,1,c0_new4.fsdb,2018-09-15T09:30:40.878265,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/partner_partner_technologymy_company_sw_tool/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X16m2fb1fs2w/full/delay_CLK_r_Q_r/control/ema/new,2947824310,2018-02-16T06:51:37
hpc-admin0.11051,fsdb,2405317631,partner,612210b3e671b9bf9459641eb291d453,,2018-02-14T05:30:44,2018-02-15T21:28:00,user01,,,1,c0.fsdb,2018-09-15T09:30:40.893790,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/partner_partner_technologymy_company_sw_tool/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X16m2fb1fs2w/full/delay_CLK_r_Q_r/control/new,2809553166,2018-02-14T05:30:44
hpc-admin0.11051,fsdb,6352033331,partner,420d734f5dc1d5fb43948f2db672b319,,2018-02-15T21:25:27,2018-02-15T21:27:59,user01,,,1,c0_new.fsdb,2018-09-15T09:30:40.097447,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/partner_partner_technologymy_company_sw_tool/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X60m2fb1fs2w/full/delay_CLK_r_Q_r/control,2908678752,2018-02-15T21:25:27
hpc-admin0.11051,fsdb,6762929436,partner,50b46f2c2fbf702b1f8a8c10c6f55c07,,2018-02-15T21:34:20,2018-02-15T21:34:20,user01,,,1,c0_new.fsdb,2018-09-15T09:30:40.107179,/my_company/scratch_space/engineering_division/partner/partner_technology/engineering_team/user/user01/partner_partner_technologymy_company_sw_tool/custom_tool/simulation/timing/tt_0p75v_0p75v_85cUHS_FCI/i128X60m2fb1fs2w/full/delay_CLK_r_Q_r/control/new,2918391401,2018-02-15T21:34:20
```

From just glancing at the data, it appears to be an issue with empty fields. For example, I'm not using custom tags nor dedupe.

Blank values should be 
```
,, or , , 
```

Works fine with JSON:
```
$ cat diskover_export_file.json | python -mjson.tool | grep '"filesize":' | head -15
        "filesize": 1855808923, 
        "filesize": 1872143765, 
        "filesize": 1619683671, 
        "filesize": 1864039435, 
        "filesize": 1857076267, 
        "filesize": 1850683799, 
        "filesize": 1857484136, 
        "filesize": 8056344320, 
        "filesize": 2269263876, 
        "filesize": 2972766162, 
        "filesize": 3162196612, 
        "filesize": 2405317631, 
        "filesize": 6352033331, 
        "filesize": 6762929436, 
        "filesize": 3202411778, 
```

**Comment by shirosaidev** [comment]
The order of the exported fields looks different than on my end, filesize should be field 4 and running cut works on my end on an export csv of files. Can you verify that you have the same results.php and export.php files as the latest on github?
The field order should be:
filename,extension,path_parent,filesize,owner,group,last_modified,last_access,last_change,hardlinks,inode,filehash,tag,tag_custom,dupe_md5,worker_name,indexing_date

**Comment by scr512** [comment]
That's strange! I'll have a look my `Dockerfile` as it clones from master and I build the image using `--no-cache` to avoid Docker being overly aggressive with it's layer caching.

Checking the MD5s from both a git clone on my server into /tmp and inside my Docker container, they match up.

```bash
# git clone https://github.com/shirosaidev/diskover-web.git
Cloning into 'diskover-web'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 2323 (delta 89), reused 80 (delta 43), pack-reused 2183
Receiving objects: 100% (2323/2323), 47.29 MiB | 18.42 MiB/s, done.
Resolving deltas: 100% (1654/1654), done.
Checking connectivity... done.
# md5sum /tmp/diskover-web/public/export.php 
eb90b3f6068b33c00516f5ae9d81b09d  export.php
# md5sum /tmp/diskover-web/public/results.php
2e9e8937e2f0845b51b3e5d214a1b66f  results.php
# docker exec -it diskover-web bash
#  md5sum /opt/diskover-web/public/export.php
eb90b3f6068b33c00516f5ae9d81b09d export.php
#  md5sum /opt/diskover-web/public/results.php
2e9e8937e2f0845b51b3e5d214a1b66f  results.php
```
I'm looking at a report I've generated through a smart searches.
URL: `http://localhost:8081/simple.php?index=diskover&index2=&submitted=true&p=1&resultsize=50&q=%21waveform&doctype=`

My search is pretty straight forward:
`extension:(fsdb OR raw)`

Looking at the header of my CSV export:
`worker_name,extension,filesize,group,filehash,dupe_md5,last_modified,last_change,owner,tag,tag_custom,hardlinks,filename,indexing_date,path_parent,inode,last_access`

**Comment by shirosaidev** [comment]
I pushed a small update to v1.5.0-rc16. Can you try to see if you can export now correctly? If not, what version of diskover was the index created with? Are you using diskover latest from github?

**Comment by scr512** [comment]
Still seeing the same issue though it appears I'm a couple of rc-releases back with diskover (diskover v1.5.0-rc14). Let me kick off a new scan using the latest release and we'll see if this issue then resolves.

**Comment by scr512** [comment]
Even with new indexes created with the latest and greatest, I'm still experiencing parsing inconsistencies. How are you testing on your side, perhaps this specific to my deployment?

**Comment by scr512** [comment]
I've done some testing. Typically, the data I'm scanning contains 10s-100s of millions of files and directories but when I ran a test scan against my personal scratch area, the CSV export functionality worked. I'm still working to get some more empirical data but it seems that either the path depth (path parent) field is perhaps causing the issue? The mangled-ness occurs irrespective of me exporting the whole dataset or just a single page.

**Comment by shirosaidev** [comment]
If you go into kibana and look at one of the docs which isn't being printed correctly in the csv, is it's source fields the same and in same order as one of the docs that is printing correctly?

**Comment by shirosaidev** [comment]
I pushed an update to rc17 just now to try to patch this in exports.php if this is the case. Try it and let's see if this fixes it.

**Comment by scr512** [comment]
Alright, I'll have a look via Kibana and I'll kick off a new scan using the fixed up exports.php.

**Comment by scr512** [comment]
Bingo! That seems to have done the trick. I can confirm the patch to exports.php addresses the issue.
